---
title: "Automatization_in_R"
author: "AR"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# 1. Установка R и полезные источники

## 1.1 Установка языка R и окружения

Что такое R?

    R — язык программирования, предназначенный для статистической обработки данных. 

Конечно, с его помощью можно сделать и сайт, и калькулятор, но основное предназначение языка заключается именно в статистических расчётах и моделировании.

Также R представляет собой свободную программную среду с открытым исходным кодом, которая распространяется абсолютно свободно и имеет бесчисленное количество обучающих и поясняющих материалов. R доступен для практически всех существующих операционных систем: Windows, Linux, macOS, и других.

Основное представительство R в сети --- сайт r-project.org (к нему мы вернёмся в следующих уроках), на котором пользователи могут не только установить самые последние обновления, но и изучить почти 11.000 пакетов, доступных для свободной загрузки и в большинстве своём снабжённых достаточно подробной документацией.

Для того, чтобы начать его использовать, R доступен для работы в командной строке используемой пользователем ОС или с помощью стандартного GUI, однако наиболее используемым и обладающим наиболее удобным интерфейсом многими считается RStudio (осторожно, это не программа для восстановления файлов).

Важное примечание: все названия папок, в которые мы собираемся устанавливать R, должны иметь названия на латинице, не содержать пробелов. Лучше, если будут только латиница и нижние подчёркивания. Чаще всего проблема возникает с именем пользователя: проверьте, соответствует ли оно рекомендациям.

    C:\Users\user_name\OneDrive\my_jobs\project 
    project_name    project-name
    username\OneDrive\myjobs\project

###### Для установки R необходимо:

    Перейти на сайт R возможно по следующей ссылке: https://cran.r-project.org;
    Выбрать установленную на компьютере операционную систему и нажать на неё:
    Скорее всего, это наша первая установка R, поэтому нажимаем на “install R for the first time” - в результате скачается полная базовая сборка R:

После этих процедур у нас будет установленный R, но доступ к нему пока что возможен исключительно через командную строку или GUI, что чаще всего решительно неудобно.

######Установка RTools

Давайте, установим инструменты Rtools с того же сайта, где мы скачивали дистрибутив языка R.

Rtools --- это набор программ, необходимых в Windows для сборки пакетов R из исходного кода.

Rtools могут пригодиться, когда мы будем работать с некоторыми пакетами в ходе анализа, например, устанавливать их не из основного хранилища CRAN. Алгоритм установки ничем не отличается от установки предыдущих программ:

    Повторяем первые два шага из урока по установке R;
    На третьем шаге выбираем RTools: 
    Устанавливаем RTools так же, как и R.

###### Установка r-base-dev для Linux.

Если у вас Linux, то этот шаг для вас!

    1)  Установим r-base-dev:
    sudo apt update
    sudo apt install r-base-dev
    2)  Готово!

######Установка RStudio

У нас установлен R и все необходимые дополнительные пакеты. Но пока что мы можем использовать R только через командную строку. Установим RStudio для того, чтобы сделать анализ данных удобным и эффективным.

    Перейдём по ссылке на сайт https://www.rstudio.com/products/rstudio/download/ ;
    Пролистаем вниз и увидим, что есть варианты установщиков для всех распространённых операционных систем

######Сопоставьте, зачем нужны указанные компоненты R - Язык программирования, ориентированный на статистическую обработку данных RStudio- Среда разработки, в которой удобно делать статистический анализ Rtools- Дополнительные компоненты для установки пакетов R

## 1.2 Самостоятельный поиск ответов на частые вопросы

В ходе статистического анализа каждый раз возникают вопросы, не имеющие быстрого решения. Даже если вы работаете (био)статистиком уже много лет, эти вопросы возникают почти каждый день, хоть с годами их и становится меньше.

Здесь мы изучим несколько способов, как искать ответы:

1.  Справка внутри R;

2.  drr.io;

3.  stackoverflow.com;

4.  Поиск ошибки в Google.

Справка внутри R

    1.    Знак вопроса (?) в сочетании с названием функции без скобок. Стоит сказать, что это работает только для уже подключённых пакетов. Например, в пакеты stats и base подключены сразу. Например: ?mean, ?sqrt, ?median:

    2.    Два знака вопроса (??) в сочетании с названием функции, термином или фразой (на английском языке). Это возвращает справку о пакетах и функциях, подходящих под запрос

Поиск информации в Сети

Иногда нужно получить большее количество информации, чем даёт справка. В таком случае мы идём в Интернет и ищем эту информацию. Рассмотрим несколько полезных способов:

    Функция RSiteSearch() перенаправляет на search.r-project.org, где представлена информация по искомому термину. Обратите внимание, что термин должен быть заключён в кавычки. Пример: RSiteSearch("biostatistics")

    Сайт rdrr.io, на котором можно найти почти то же самое, что и выше, но нужно напрямую искать: 

    Сайт stackoverflow.com — это жемчужина поиска ответов на вопросы для статистиков/программистов и почти всех, кто связан с компьютерами. В отличие от предыдущих двух сайтов этот наполняется людьми, которые задают вопросы и дают на них ответы. Почти всегда можно найти ответ на свой вопрос и увидеть многочисленные варианты его решения: 


# 2. RStudio  и создание проектов
## 2.1 Интерфейс RStudio
